// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZriXF-AIKI6RqL9MGvSLNyteUBiciBfM',
    appId: '1:955551592299:android:0e51940288aae85d7b262e',
    messagingSenderId: '955551592299',
    projectId: 'palakat-e70af',
    storageBucket: 'palakat-e70af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANoigma8YvfmJGdUs3-FQHWKwDl4lGcRI',
    appId: '1:955551592299:ios:7d231d2102491c4a7b262e',
    messagingSenderId: '955551592299',
    projectId: 'palakat-e70af',
    storageBucket: 'palakat-e70af.appspot.com',
    androidClientId: '955551592299-t80cuphg38tsd5i4d7i8uilnrpsmqlip.apps.googleusercontent.com',
    iosClientId: '955551592299-bfs7bprap04kmncka1tpa4okhvi5p3dp.apps.googleusercontent.com',
    iosBundleId: 'com.meimodev.palakat.palakat',
  );

}